version: '3'

services:
  php:
    build: .
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html/task-manager
    networks:
      - app-network
  
  db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8091:80"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
